[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3 -m gunicorn app:app --bind 0.0.0.0:$PORT"
